### PR TITLE
Update notification text

### PR DESCRIPTION
**Pull request by jpamental**
## Summary

Added node title, revision author, and log comment to notification email when submitted for review.

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| Documentation reflects changes? | no
| `CHANGELOG` reflects changes? | yes
| Unit/Functional tests reflect changes? | no
| Did you perform browser testing? | no
| Risk level | Low
| Relevant links | JIRA issue
https://thinkoomph.jira.com/browse/RIG-277?atlOrigin=eyJpIjoiMWZjMjJjZjBjYWQ1NGEzMWJiYjY4OTY4YTE0YmQwYzYiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by ben-hamelin** [comment]
@jpamental Update looks good, we will need an update hook to ensure all sites get this change.
For example see update hook 9047: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/blob/master/ecms_base/ecms_base.install#L750

New hook should be 9051, and you just need to change newConfig to ```$newConfig = [
    'content_moderation_notifications.content_moderation_notification.ready_for_review',
  ];```

Also trying to figure out why these tests aren't passing

**Comment by ben-hamelin** [comment]
Also need a CHANGELOG entry

**Review by ben-hamelin — CHANGES_REQUESTED** [review]
update hook & changelog entry

**Comment by jpamental** [comment]
Added CHANGELOG message and update hook (@ben-hamelin can you check my work? :) )

**Comment by ben-hamelin** [comment]
@jpamental Almost there! You need all of the following in that update hook:
```
  // Config updates.
  $path = \Drupal::service('extension.list.profile')->getPath('ecms_base');

  /** @var \Drupal\Core\Config\StorageInterface $active_storage */
  $active_storage = \Drupal::service('config.storage');

  /** @var \Drupal\Core\Config\FileStorage $profile_install_source */
  $profile_install_source = new FileStorage($path . "/config/install/");

  $newConfig = [ 
    'content_moderation_notifications.content_moderation_notification.ready_for_review', 
  ];

  foreach ($newConfig as $config) {
    $active_storage->write("{$config}", $profile_install_source->read("{$config}"));
  }

**Comment by jpamental** [comment]
Checks now passing @ben-hamelin !

**Review by ben-hamelin — APPROVED** [review]
Ok this is all set!
/approved

**Pull request merged**
