### PR TITLE
Add disable languages module

### PR DESCRIPTION
**Pull request by ben-hamelin**
## Summary

Adds disable language module to base install. Includes permissions and base settings config.
Did not write update hook, as this will be a simple update to existing COVID site.

## Metadata

| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| Documentation reflects changes? | no
| `CHANGELOG` reflects changes? | yes
| Unit/Functional tests reflect changes? | no
| Did you perform browser testing? | yes
| Risk level | Low
| Relevant links | JIRA issue, bug reports, security alerts, etc.

### CODE REVIEW

**Review by pfrilling — APPROVED** [review]
Looks good!

**Comment by pfrilling** [comment]
A few questions:
1. Do you need to add an update hook to install the module?
2. Can the anonymous user view a language node in a disabled language?

**Comment by ben-hamelin** [comment]
@pfrilling 
Added update hook for release 0.2.0
Anonymous viewers will not have permission to view disabled languages, that actually drives the visibility of the language switcher element

**Review by pfrilling — APPROVED** [review]
Still looks good. 🍻

**Pull request merged**
