### PR TITLE
Permissions refinement

### PR DESCRIPTION
**Pull request by pfrilling**
## Summary
The permissions on the Covid site were incorrect. This updates the permissions for the author/publisher/site admin roles to set the correct default permissions for a base installation. Will need to circle back to the optional content types to ensure those permissions are provided correctly on module installation.

## Metadata
| Question | Answer |
|----------|--------|
| Did you use a meaningful pull request title? | yes
| Did you apply meaningful labels to the pull request? | yes
| Did you perform a self review first? | yes
| Documentation reflects changes? | no
| `CHANGELOG` reflects changes? | yes
| Unit/Functional tests reflect changes? | no
| Did you perform browser testing? | yes
| Risk level | High
| Relevant links | [RIG-161](https://thinkoomph.jira.com/browse/rig-161)

### CODE REVIEW

**Comment by ben-hamelin** [comment]
Looks good!
/approved

**Comment by pfrilling** [comment]
@ben-hamelin, I rebased my branch and updated your configuration writes in the hook_update function.

**Comment by ben-hamelin** [comment]
Yep, I like that approach.
Looks good!
/approved

**Comment by pfrilling** [comment]
@ben-hamelin, I added some additional module code to get the layout builder/media library issue fixed. Can you take one more look? I don't know why the testing is throwing a segmentation fault 🤷. I'm going to ignore it if it happens again.

**Comment by ben-hamelin** [comment]
Yep, this all looks good.
/approved

**Pull request merged**
